[versions]
androidGradlePlugin = "8.1.2"
kotlin = "1.9.0"

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }